### ISSUE TITLE
irrecoverable error when referencing unknown msmtp account

### ISSUE THREAD

**Issue by bbbart** [sumnerevans/offlinemsmtp#3]
After a clean install of `offlinemsmtp` on arch, I configured my `mutt` according to the README on github. Offlinemsmtp didn't work and my user journal consistently gave the following error:

```
Traceback (most recent call last):
  File "/usr/bin/offlinemsmtp", line 33, in <module>
    sys.exit(load_entry_point('offlinemsmtp==0.3.8', 'console_scripts', 'offlinemsmtp')>
  File "/usr/lib/python3.10/site-packages/offlinemsmtp/__main__.py", line 82, in main
    Daemon.run(args)
  File "/usr/lib/python3.10/site-packages/offlinemsmtp/daemon.py", line 180, in run
    daemon.flush_queue()
  File "/usr/lib/python3.10/site-packages/offlinemsmtp/daemon.py", line 65, in flush_qu>
    if not self.can_send_message(msmtp_args, message_content):
  File "/usr/lib/python3.10/site-packages/offlinemsmtp/daemon.py", line 142, in can_sen>
    socket_open = sock.connect_ex((host, port))
UnboundLocalError: local variable 'host' referenced before assignment
```
With some `breakpoint()` magic, I figured out that the root cause was my blindly copy pasting `set sendmail = 'offlinemsmtp -a personal'` into my `.muttrc`, where "personal" simply doesn't exist as an `msmtp` account on my machine.

So, I figured it out, and fixed the problem (also by editing the content of the files already in my offlinemsmtp-queue), but I still wanted to let it be known here that a configuration mistake as described above doesn't lead to a warning, but to a fatal error with a seemingly unrelated error message.

Happy now to finally start using `offlinemsmtp` in earnest! :-)

**Comment by sumnerevans** [comment]
I think this was fixed in 8073213. What version are you using?

**Comment by bbbart** [comment]
0.3.8-2, the latest one currently available from the AUR

**Comment by sumnerevans** [comment]
That's so old. I don't use Arch anymore, so I don't keep it up-to-date. I just disowned the package. Please run a more recent version for the latest bug fixes.

**Comment by bbbart** [comment]
Okay. I adopted the package and just pushed a new package to the AUR for version 0.3.10. (my first AUR contribution, yay! :-))

**Comment by sumnerevans** [comment]
Awesome, thanks!
