### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by bbbart** [sumnerevans/offlinemsmtp#4]
I'm using `offlinemsmtp` with [twmn](https://github.com/sboli/Twmn). The notifications as such work fine, except:

- the `offlinemsmtp` service doesn't start if the `twmn` service wasn't started yet, or failed for whatever reason. This is not always apparent at first, which leaves me piling up messages in `~/.offlinemsmtp-outbox` unwittingly while online. Moreover, it doesn't allow me to run `offlinemsmtp` when not logged in to an X server :-(
- when all is working fine, the sending notifications seem to remain in the corner of my screen forever. If I interpret the code correctly, https://github.com/sumnerevans/offlinemsmtp/blob/master/offlinemsmtp/daemon.py#L71 tries to keep the notification active to 10 minutes: that seems overly long :-)

@sumnerevans, what is your position on pull requests? Would you accept changes to address the points above? Perhaps making them configurable?

**Comment by sumnerevans** [comment]
You can submit a PR, yes. I'll merge it if it's good.

Regarding disabling notifications, there's a `--silent` flag that will disable notifications. That can help you if you don't have a graphical environment.

Regrading the notifications in the corner, https://github.com/sumnerevans/offlinemsmtp/blob/master/offlinemsmtp/daemon.py#L77 should dismiss it. Maybe your window manager is not handling that signal correctly? The intent is for it to show "Sending..." until it's sent or errored.

**Comment by bbbart** [comment]
Yes, you're right about the notifications: I switched from `twmn` to `dunst` and it all makes much more sense now. :-)

Except, yesterday I was offline for a long time, and after 'sending' a few emails, I got more and more notifications about (re-)queued messages every minute or so. I'm guessing that's why the `--send-mail-file` option exists?

Let me look into a possible PR, thanks!

**Comment by sumnerevans** [comment]
The interval of trying to resend the messages is set here: https://github.com/sumnerevans/offlinemsmtp/blob/master/offlinemsmtp/__main__.py#L28

The `--send-mail-file` is mainly there so that you can queue up messages even while online, but it can be used for disabling trying to send all of the mail every couple minutes as well. It does still cause a notification every period, but it's just one, not one for every message.
