### ISSUE TITLE
watchdog -> inotify?

### ISSUE THREAD

**Issue by bbbart** [sumnerevans/offlinemsmtp#5]
Recently I had some people complaining about attachments in mails I sent through offlinemsmtp being "broken". After some research, I found the problem: 'larger' attachments were indeed broken, because offlinemsmtp started sending the email before the queue-file was completely written.

https://github.com/sumnerevans/offlinemsmtp/blob/25536f1a59790c6185136e5c9b09bb9b2800e950/offlinemsmtp/daemon.py#L44

was not enough. Changing the `1` to, say, `5` solved my issue, but I obviously don't like that approach. :-)

I found that watchdog doesn't support waiting for the closure of a new file, but inotify does (on Linux, at least).

Is there an interest to replace watchdog with pynotify in offlinemsmtp? If so, I might be interested in taking up the task.

**Comment by bbbart** [comment]
or, perhaps https://docs.python.org/3/library/os.html#os.fsync is an easier solution?

**Comment by sumnerevans** [comment]
fsync probably still puts the file on disk before it's done writing, so the daemon will still pick up the file too quickly. I'm fine if you want to try implementing some other listener library. If the code is good, I'll merge it. As you can tell, I've run into this problem myself as well.

**Comment by bbbart** [comment]
Maybe a silly idea, but what if we would add another line to the bottom of the queue file which is identical to the first line added (with the `msmtp` arguments), and then have the daemon verify if both lines are the same, before taking any action?

This way, the least amount of code needs to be changed, and we cater for arbitrarily large mail sizes.

Any thoughts?

**Comment by bbbart** [comment]
I implemented a daemon based on inotify in PR #6 

A first few tests here locally seem to work perfectly fine. Before I was having issues starting from emails sized at 2.5MB or larger. Now I tested up to 8MB and found no broken attachments.

(I had to loosen the dependency specification on `jedi` in order to be able to install `pudb`, my preferred debugger.)
